name: E2E Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
          check-latest: true

      - uses: actions/checkout@v4

      - uses: technote-space/get-diff-action@v6.1.2
        id: git-diff
        with:
          PATTERNS: |
            +(src|__tests__)/**/*.go

      - name: Test E2E
        if: steps.git-diff.outputs.diff
        run: |
          make build
